version: '3.2'

services:
  tester:
    image: "selenium/standalone-chrome:3.14"
    restart: always
    ports:
      - 4444:4444
    networks:
      - selenium

networks:
  selenium:
    driver: bridge

