version: '3.2'

services:
  tester:
    image: "selenium/standalone-chrome:3.14"
    restart: always
    ports:
      - 4444
    networks:
      - selenium
  runner:
    build: 
      context: ..
    command: "/root/shiblogin.sh devcontainer"      
    networks:
      - selenium
    volumes:
      - "..:/workspace"
#      - type: bind
#        source: "./userdata/"
#        target: "/workdir/userdata"
#        read_only: true

networks:
  selenium:
    driver: bridge

