version: '3.2'

secrets:
  bupw:
    file: "~/.bupw.json"

services:
  tester:
    image: "selenium/standalone-chrome"
    restart: always
    ports:
      - 4444
    networks:
      - selenium
  runner:
    build: 
      context: ..
    command: "/root/shiblogin.sh devcontainer"      
    networks:
      - selenium
    secrets:
      - source: bupw
        target: bupw.json
    environment:
      - SHIB_PW_FILE=/run/secrets/bupw.json
      - SELENIUM_SERVER=tester
    volumes:
      - "..:/workspace"
#      - type: bind
#        source: "./userdata/"
#        target: "/workdir/userdata"
#        read_only: true

networks:
  selenium:
    driver: bridge

